title: Andrew Wheeler GitHub Blog
author: Andrew Wheeler
email: apwheele@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  To host things I cannot on my free wordpress site

# social links
twitter_username: CrimAndyW
github_username:  apwheele

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima